name: alpine-release

on:
  push:
    branches:
      - main
      - cicd
    tags:
      - v*

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          packages: >
            build-base
            libgit2-dev
            meson
            libpulse
            opus
            lame-libs
            lame
            lame-dev
            xz
            protobuf
            cargo
            rust
      
 
      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@9aaabdb5e989894e95288328d8b17a6347217ae3
        env:
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 0.1.0
          TAG_CONTEXT: repo
 
      - name: Run build inside Alpine chroot as root
        run: |
          cargo build --release
          tar cJf ./rfbproxy.tar.xz --owner=0:0 --transform=s@target/release@usr/bin@ target/release/rfbproxy
        shell: alpine.sh --root {0}
        
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}
        with:
          tag_name: ${{ steps.bump-version.outputs.tag }}
          release_name: ${{ steps.bump-version.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./rfbproxy.tar.xz
          asset_name: rfbproxy.tar.xz
          asset_content_type: application/octet-stream
